<?php

/**
 * Original Nexus SBI4U course plan mapped to the Ontario Curriculum, Grades 11 and 12:
 * Science, 2008 (revised). The attached videos are user-authored source material.
 */

declare(strict_types=1);

return [
    'course' => [
        'title' => 'Biology, Grade 12, University Preparation',
        'code' => 'SBI4U',
        'curriculum' => 'The Ontario Curriculum, Grades 11 and 12: Science, 2008 (revised)',
        'pathway' => 'Learn - Watch - Read - Understand - Practice - Check - Investigate - Evaluate - Reflect - Progress',
    ],
    'units' => [
        1 => [
            'section' => 2,
            'title' => 'Unit 1 - Biochemistry',
            'book' => 'Learning Material - Unit 1: Biochemistry',
            'overall' => ['B1', 'B2', 'B3'],
            'chapters' => [
                ['id' => 'u1_foundations', 'title' => '1.1 Foundations: The Chemical Basis of Life', 'expectations' => ['B2.1', 'B3.5'], 'vocabulary' => 'atom, ion, isotope, covalent bond, ionic bond, oxidation-reduction, hydrolysis, condensation, neutralization', 'explanation' => 'Life depends on chemical reactions that rearrange matter while conserving atoms and transferring energy. Bond polarity, electron distribution, and functional groups determine how molecules interact. Oxidation-reduction transfers electrons; hydrolysis uses water to split molecules; condensation joins subunits; neutralization changes acid-base conditions.', 'example' => 'Trace the atoms and electron transfer when glucose is oxidized during cellular respiration, then classify the reaction as redox rather than merely “breaking food apart.”', 'stse' => 'Radioisotope tracers allow scientists to follow molecules through cells while requiring careful evaluation of exposure and disposal.', 'checks' => ['How does bond polarity influence molecular interactions?', 'How can you distinguish hydrolysis from condensation?', 'Why is a redox reaction an electron-transfer process?'], 'misconception' => 'Chemical bonds do not “contain energy” that is simply released; net energy change depends on bonds broken and formed.', 'videos' => ['Unit-1/Chapter-1/1-Fundamental Chemistry of Life.mp4']],
                ['id' => 'u1_water', 'title' => '1.2 Water and Biological Systems', 'expectations' => ['B2.1', 'B3.2', 'B3.3'], 'vocabulary' => 'polarity, hydrogen bond, cohesion, adhesion, specific heat capacity, solvent, hydrophilic, hydrophobic', 'explanation' => 'Water is polar because oxygen attracts shared electrons more strongly than hydrogen. Hydrogen bonding explains cohesion, surface tension, high specific heat capacity, and strong solvent behaviour. These properties stabilize cellular temperature and allow ions and polar solutes to move through aqueous environments.', 'example' => 'Compare the behaviour of sodium chloride, glucose, and oil in water by connecting each observation to charge distribution and intermolecular attraction.', 'stse' => 'Water quality and dissolved contaminants influence membrane transport, enzyme activity, and organism health.', 'checks' => ['Why does water resist rapid temperature change?', 'Why do non-polar molecules aggregate in water?', 'How does water support transport in organisms?'], 'misconception' => 'Hydrogen bonds are intermolecular attractions, not covalent bonds within a water molecule.', 'videos' => ['Unit-1/Chapter-1/2-Water-Life_s Solvent.mp4']],
                ['id' => 'u1_carbon', 'title' => '1.3 Carbon Chemistry and Functional Groups', 'expectations' => ['B2.1', 'B2.3', 'B3.3'], 'vocabulary' => 'carbon skeleton, isomer, hydroxyl, carbonyl, carboxyl, amino, phosphate, methyl', 'explanation' => 'Carbon forms four covalent bonds and can build chains, rings, and branched structures. Functional groups change polarity, acidity, basicity, and reactivity. Structural isomers share a molecular formula but differ in arrangement, producing different biological properties.', 'example' => 'Identify the hydroxyl and carbonyl groups in a sugar model, then predict how each group affects solubility and reactivity.', 'stse' => 'Molecular modelling supports drug design by predicting how functional groups interact with a target protein.', 'checks' => ['Why can carbon form diverse biological molecules?', 'How does a carboxyl group affect acidity?', 'Why can isomers have different functions?'], 'misconception' => 'Molecules with the same formula are not necessarily biologically equivalent.', 'videos' => ['Unit-1/Chapter-1/3-The Carbon Chemistry of Life.mp4']],
                ['id' => 'u1_carbs_lipids', 'title' => '1.4 Carbohydrates and Lipids', 'expectations' => ['B2.3', 'B2.4', 'B3.2'], 'vocabulary' => 'monosaccharide, polysaccharide, glycosidic bond, triglyceride, phospholipid, saturated, unsaturated', 'explanation' => 'Carbohydrates provide rapid energy, energy storage, and structural support. Lipids are largely non-polar and serve in long-term energy storage, insulation, signalling, and membranes. The shape and bonding of each molecule explain its cellular role.', 'example' => 'Compare glycogen, starch, and cellulose by linking branching and bond orientation to storage or structural function.', 'stse' => 'Food testing and nutrition claims should be evaluated using evidence about molecular structure, quantity, and metabolism rather than labels alone.', 'checks' => ['How do storage polysaccharides differ from cellulose?', 'Why do phospholipids form bilayers?', 'How does unsaturation affect membrane fluidity?'], 'misconception' => 'All lipids are not “fats”; the class also includes phospholipids and steroids.', 'videos' => ['Unit-1/Chapter-1/4-Carbohydrates and Lipids.mp4']],
                ['id' => 'u1_proteins_nucleic', 'title' => '1.5 Proteins and Nucleic Acids', 'expectations' => ['B2.3', 'B3.2', 'B3.3'], 'vocabulary' => 'amino acid, peptide bond, primary structure, tertiary structure, nucleotide, phosphodiester bond, DNA, RNA', 'explanation' => 'A protein’s amino-acid sequence drives folding and therefore function. Nucleic acids store, transmit, and help express biological information. Both are polymers built through condensation and separated through hydrolysis, but their monomers and cellular roles differ.', 'example' => 'Explain how replacing one charged amino acid with a non-polar amino acid could alter folding and protein activity.', 'stse' => 'Protein and nucleic-acid analysis underpin diagnostic tests, therapeutic proteins, and personalized medicine.', 'checks' => ['How does primary structure influence tertiary structure?', 'What bonds join nucleotides?', 'How do DNA and RNA roles differ?'], 'misconception' => 'Denaturation changes protein shape and function but usually does not break every peptide bond.', 'videos' => ['Unit-1/Chapter-1/5-Proteins and Nucleic Acids.mp4']],
                ['id' => 'u1_enzymes', 'title' => '1.6 Enzymes and Biochemical Reactions', 'expectations' => ['B1.1', 'B2.5', 'B3.4'], 'vocabulary' => 'activation energy, active site, substrate, induced fit, competitive inhibition, allosteric inhibition, denaturation', 'explanation' => 'Enzymes lower activation energy by orienting substrates and stabilizing transition states without changing the reaction’s overall energy balance. Temperature, pH, concentration, cofactors, and inhibitors alter reaction rate. Enzyme structure explains specificity and regulation.', 'example' => 'Interpret a reaction-rate graph to distinguish substrate saturation from enzyme denaturation.', 'stse' => 'Enzymes improve food production and pharmaceuticals while reducing energy use; claims must be assessed against reaction conditions and evidence.', 'checks' => ['What does an enzyme change about a reaction?', 'Why does rate plateau at high substrate concentration?', 'How do competitive and allosteric inhibitors differ?'], 'misconception' => 'Enzymes do not make non-spontaneous reactions energetically favourable; they change rate, not overall free-energy change.', 'videos' => ['Unit-1/Chapter-1/6-Enzymes.mp4']],
                ['id' => 'u1_cells', 'title' => '1.7 Cell Structures and Biochemical Organization', 'expectations' => ['B1.2', 'B3.1'], 'vocabulary' => 'nucleus, ribosome, endoplasmic reticulum, Golgi apparatus, lysosome, mitochondrion, vacuole', 'explanation' => 'Eukaryotic cells partition functions among organelles. The endomembrane system synthesizes, modifies, and transports products; lysosomes digest materials; mitochondria convert energy; ribosomes assemble proteins. Compartmentalization allows incompatible processes to occur efficiently.', 'example' => 'Follow a secreted protein from transcription through ribosome, rough ER, Golgi apparatus, vesicle, and plasma membrane.', 'stse' => 'Fluorescent labels and medical imaging reveal cellular organization and help diagnose disease.', 'checks' => ['Why is compartmentalization advantageous?', 'How are rough ER and Golgi functions connected?', 'What evidence links organelle malfunction to disease?'], 'misconception' => 'Organelles do not work independently; cellular function emerges from coordinated transport and signalling.', 'videos' => ['Unit-1/Chapter-2/1-Cell Structures.mp4']],
                ['id' => 'u1_membranes', 'title' => '1.8 Membrane Structure and Function', 'expectations' => ['B3.6'], 'vocabulary' => 'fluid mosaic model, phospholipid bilayer, membrane protein, cholesterol, glycoprotein, selective permeability', 'explanation' => 'The fluid mosaic model describes a dynamic phospholipid bilayer with embedded proteins, cholesterol, and carbohydrates. Hydrophobic and hydrophilic interactions create selective permeability; membrane proteins support transport, signalling, adhesion, and recognition.', 'example' => 'Predict how increased saturated fatty acids or reduced cholesterol would affect membrane fluidity at different temperatures.', 'stse' => 'Drug delivery systems use lipid vesicles to move therapeutic molecules across biological barriers.', 'checks' => ['Why is the bilayer selectively permeable?', 'What roles do membrane proteins play?', 'How does cholesterol buffer fluidity?'], 'misconception' => 'The membrane is not a rigid wall; many components move laterally.', 'videos' => ['Unit-1/Chapter-2/2-Membrane Structutre and Functions.mp4']],
                ['id' => 'u1_transport', 'title' => '1.9 Transport Across Membranes', 'expectations' => ['B2.2', 'B2.5', 'B3.6'], 'vocabulary' => 'diffusion, osmosis, facilitated diffusion, active transport, concentration gradient, endocytosis, exocytosis', 'explanation' => 'Passive transport moves substances down electrochemical gradients; active transport couples movement against a gradient to an energy source. Osmosis depends on water potential and membrane permeability. Bulk transport moves large particles or volumes through vesicles.', 'example' => 'Use initial and final mass data from potato cores to estimate the isotonic point and explain sources of uncertainty.', 'stse' => 'Dialysis applies selective permeability and diffusion to remove wastes when kidney function is impaired.', 'checks' => ['When is a transport protein required?', 'How does active transport differ from facilitated diffusion?', 'How can osmosis data reveal solute concentration?'], 'misconception' => 'Water moves in both directions; net osmosis reflects unequal rates, not one-way movement.', 'videos' => ['Unit-1/Chapter-2/3-Transport across Membranes.mp4']],
            ],
            'practice' => ['Biochemical Evidence Case Study', 'Membrane Transport Data Analysis'],
            'lab' => 'Enzyme and Membrane Investigation using supplied data',
            'assignment' => 'Evaluate a cellular-biotechnology application and explain its biochemical mechanism.',
        ],
        2 => [
            'section' => 3,
            'title' => 'Unit 2 - Metabolic Processes',
            'book' => 'Learning Material - Unit 2: Metabolic Processes',
            'overall' => ['C1', 'C2', 'C3'],
            'chapters' => [
                ['id' => 'u2_metabolism', 'title' => '2.1 Metabolism, Energy, and Thermodynamics', 'expectations' => ['C1.2', 'C2.1', 'C3.3'], 'vocabulary' => 'metabolism, anabolic, catabolic, free energy, entropy, coupled reaction', 'explanation' => 'Metabolism is the coordinated network of anabolic and catabolic reactions. The first law tracks energy transformation; the second explains why every transfer increases entropy. Cells couple energy-releasing reactions to energy-requiring work through carriers such as ATP and electron carriers.', 'example' => 'Build an energy-accounting diagram that connects glucose oxidation to ATP synthesis and heat loss.', 'stse' => 'Metabolic claims about diets and supplements must be evaluated using cellular evidence, dosage, and risk.', 'checks' => ['How are anabolic and catabolic pathways coupled?', 'Why is cellular energy transfer never perfectly efficient?', 'What makes a reaction exergonic?'], 'misconception' => 'Cells do not create energy; they transform and transfer it.', 'videos' => ['Unit-2/Chapter-3/U-2-Ch-3-L-1(3) Metabolism and Energy.mp4', 'Unit-2/Chapter-3/U-2 Ch-3 L-3.4(3)Food as Fuel.mp4']],
                ['id' => 'u2_atp_enzymes', 'title' => '2.2 ATP and Metabolic Enzymes', 'expectations' => ['C2.1', 'C3.3'], 'vocabulary' => 'ATP, phosphorylation, activation energy, enzyme, feedback inhibition, allosteric regulation', 'explanation' => 'ATP hydrolysis can be coupled to transport, movement, and synthesis by transferring phosphate or changing protein conformation. Enzymes organize pathways, while feedback inhibition prevents unnecessary product accumulation and stabilizes cellular conditions.', 'example' => 'Explain how ATP hydrolysis can drive an otherwise endergonic reaction when the coupled total free-energy change is negative.', 'stse' => 'Inherited enzyme deficiencies show how disruption of one pathway step can affect the whole organism.', 'checks' => ['Why is ATP called an energy carrier?', 'How does feedback inhibition regulate a pathway?', 'Why must ATP be continuously regenerated?'], 'misconception' => 'ATP is not long-term energy storage; it is a rapidly recycled transfer molecule.', 'videos' => ['Unit-2/Chapter-3/2-3-L-3.2(3) ATP-Energy Currency of the Cell.mp4', 'Unit-2/Chapter-3/2-3-L-3.3(3)Enzymes and Activation Energy.mp4']],
                ['id' => 'u2_resp_intro', 'title' => '2.3 Cellular Respiration and Fermentation', 'expectations' => ['C2.2', 'C3.1'], 'vocabulary' => 'glycolysis, pyruvate, acetyl-CoA, fermentation, aerobic, anaerobic, substrate-level phosphorylation', 'explanation' => 'Glycolysis splits glucose and produces a small ATP yield plus reduced electron carriers. In oxygen-rich conditions, pyruvate enters mitochondrial pathways; without sufficient oxygen, fermentation regenerates NAD+ so glycolysis can continue. Products and efficiency differ across pathways.', 'example' => 'Use carbon counts and electron carriers to track glucose through glycolysis and fermentation.', 'stse' => 'Fermentation supports food production and biotechnology, while exercise physiology illustrates temporary limits on aerobic supply.', 'checks' => ['Why must NAD+ be regenerated?', 'Where is ATP made during glycolysis?', 'How do alcoholic and lactate fermentation differ?'], 'misconception' => 'Fermentation does not produce most of its ATP after glycolysis; its key role is NAD+ regeneration.', 'videos' => ['Unit-2/Chapter-4/2-4-L-4.1(3)Introduction to Cellular Respiration and Fermentation.mp4']],
                ['id' => 'u2_aerobic', 'title' => '2.4 Aerobic Respiration: Pyruvate to ATP', 'expectations' => ['C3.1', 'C3.4'], 'vocabulary' => 'pyruvate oxidation, citric acid cycle, NADH, FADH2, electron transport chain, chemiosmosis, ATP synthase', 'explanation' => 'Pyruvate oxidation and the citric acid cycle release carbon dioxide and load electron carriers. The electron transport chain uses electron energy to pump protons; chemiosmosis drives ATP synthase. Oxygen accepts electrons and protons, forming water.', 'example' => 'Interpret a pathway diagram to locate carbon loss, electron-carrier reduction, proton pumping, and ATP production.', 'stse' => 'Mitochondrial disorders illustrate why tissues with high energy demand are especially vulnerable to impaired respiration.', 'checks' => ['What is oxygen’s role?', 'How does a proton gradient drive ATP synthesis?', 'Where is carbon dioxide generated?'], 'misconception' => 'Oxygen is not directly used in glycolysis or the citric acid cycle; it is the final electron acceptor.', 'videos' => ['Unit-2/Chapter-4/2-4-L-4.2(3)Aerobic RespirationThe Details.mp4', 'Unit-2/Chapter-4/2-4-L-4.3(3) The Efficiency and Regulation of Cellular Respiration.mp4']],
                ['id' => 'u2_anaerobic', 'title' => '2.5 Anaerobic Pathways and Metabolic Trade-offs', 'expectations' => ['C1.2', 'C3.1', 'C3.4'], 'vocabulary' => 'anaerobic respiration, fermentation, oxygen debt, metabolic rate, efficiency', 'explanation' => 'Anaerobic pathways sustain ATP production when oxygen-dependent electron transport is limited, but their ATP yield per glucose is lower. Organisms balance rate, efficiency, substrate availability, and waste products under different environmental conditions.', 'example' => 'Compare ATP yield and end products for aerobic respiration, lactate fermentation, and alcoholic fermentation.', 'stse' => 'Understanding metabolic limits informs training, medical treatment, wastewater systems, and industrial bioreactors.', 'checks' => ['Why can fermentation be rapid but inefficient?', 'What determines pathway choice?', 'How does oxygen availability affect ATP yield?'], 'misconception' => 'Anaerobic does not always mean fermentation; some organisms use alternative final electron acceptors.', 'videos' => ['Unit-2/Chapter-4/2-4-L-4.4(3)Anaerobic Pathways-Life without Oxygen.mp4']],
                ['id' => 'u2_photo_intro', 'title' => '2.6 Photosynthesis: Capturing Light Energy', 'expectations' => ['C2.3', 'C3.2'], 'vocabulary' => 'chloroplast, pigment, absorption spectrum, photosystem, photolysis, thylakoid, stroma', 'explanation' => 'Pigments absorb selected wavelengths and transfer energy to reaction centres. Light-dependent reactions split water, release oxygen, reduce NADP+, and build a proton gradient for ATP synthesis. Chloroplast structure separates these processes from carbon fixation.', 'example' => 'Relate an action spectrum to pigment absorption and predict which light colours most strongly support photosynthesis.', 'stse' => 'Controlled-environment agriculture manipulates light spectrum and intensity to improve yield while managing energy use.', 'checks' => ['Where does released oxygen originate?', 'Why are multiple pigments useful?', 'How is ATP made in chloroplasts?'], 'misconception' => 'Plants do not obtain most of their biomass from soil; carbon dioxide supplies the carbon.', 'videos' => ['Unit-2/Chapter-5/Photosynthesis-An Introduction.mp4']],
                ['id' => 'u2_calvin', 'title' => '2.7 Carbon Fixation and Photosynthetic Pathways', 'expectations' => ['C3.2', 'C3.4'], 'vocabulary' => 'Calvin cycle, carbon fixation, RuBisCO, G3P, C3, C4, CAM, photorespiration', 'explanation' => 'The Calvin cycle uses ATP and NADPH to reduce fixed carbon and regenerate its carbon-accepting molecule. C4 and CAM pathways concentrate carbon dioxide or separate steps in space or time, reducing photorespiration under hot or dry conditions.', 'example' => 'Compare C3, C4, and CAM trade-offs in water conservation, energy cost, and habitat.', 'stse' => 'Crop engineering aims to improve carbon fixation but must be evaluated for ecological, economic, and food-system effects.', 'checks' => ['What enters and leaves the Calvin cycle?', 'Why can RuBisCO reduce efficiency?', 'How do C4 and CAM plants limit water loss?'], 'misconception' => 'The “dark reactions” do not require darkness; they depend indirectly on products of light reactions.', 'videos' => ['Unit-2/Chapter-5/Pathways_of_Photosynthesis.mp4', 'Unit-2/Chapter-5/Alternative Mechanisms of Carbon Fixation.mp4']],
                ['id' => 'u2_compare', 'title' => '2.8 Comparing Photosynthesis and Respiration', 'expectations' => ['C1.1', 'C3.3', 'C3.4'], 'vocabulary' => 'matter cycling, energy flow, redox, electron carrier, chemiosmosis, producer, consumer', 'explanation' => 'Photosynthesis stores energy by reducing carbon; respiration releases usable energy by oxidizing organic molecules. Both use membranes, electron carriers, proton gradients, and ATP synthase. Matter cycles among systems, while energy flows and is ultimately dissipated as heat.', 'example' => 'Construct a comparison table for location, inputs, outputs, electron source, final acceptor, and biological purpose.', 'stse' => 'Bioremediation and wastewater treatment use microbial metabolism to transform contaminants and nutrients.', 'checks' => ['Which features are shared?', 'How are overall redox directions opposite?', 'Why do plants also respire?'], 'misconception' => 'Photosynthesis and respiration are not exact reversals at every step, despite complementary overall equations.', 'videos' => ['Unit-2/Chapter-5/Photosynthesis and Cellular Respiration-A Comparison.mp4']],
            ],
            'practice' => ['Respiration Pathway Evidence Analysis', 'Photosynthesis Rate and Limiting Factors'],
            'lab' => 'Virtual investigation of respiration and photosynthesis products using supplied observations',
            'assignment' => 'Analyse a metabolic technology or personal-health claim using pathway evidence.',
        ],
        3 => [
            'section' => 4,
            'title' => 'Unit 3 - Molecular Genetics',
            'book' => 'Learning Material - Unit 3: Molecular Genetics',
            'overall' => ['D1', 'D2', 'D3'],
            'chapters' => [
                ['id' => 'u3_inheritance', 'title' => '3.1 Molecular Basis and History of Inheritance', 'expectations' => ['D3.7'], 'vocabulary' => 'transformation, bacteriophage, nucleotide, double helix, antiparallel, complementary', 'explanation' => 'Evidence from transformation, bacteriophage, base-composition, and diffraction studies established DNA as hereditary material and constrained the double-helix model. Scientific knowledge developed through converging evidence and collaborative, sometimes inequitable, contributions.', 'example' => 'Explain how a labelled-phage experiment distinguishes whether protein or DNA enters a bacterial cell.', 'stse' => 'Historical analysis should credit evidence, collaboration, and the ethical treatment of contributors and data.', 'checks' => ['What evidence identified DNA as hereditary material?', 'Why does complementary pairing matter?', 'How did multiple methods support the model?'], 'misconception' => 'No single experiment or scientist alone established the modern DNA model.', 'videos' => ['Unit-3/Chapter-6/The Molecular Basis of Inheritance.mp4', 'Unit-3/Chapter-6/DNA Structure and Function-A History.mp4']],
                ['id' => 'u3_organization', 'title' => '3.2 DNA and Genome Organization', 'expectations' => ['D2.1', 'D3.2'], 'vocabulary' => 'chromosome, chromatin, nucleosome, plasmid, operon, genome, coding sequence, regulatory sequence', 'explanation' => 'Prokaryotic and eukaryotic genomes differ in chromosome form, packaging, compartmentalization, and regulation. Histone-associated chromatin compacts eukaryotic DNA while remaining dynamically accessible. Genome organization influences replication and gene expression.', 'example' => 'Compare the expected location and regulation of a gene in a bacterial operon and a eukaryotic chromosome.', 'stse' => 'Genome databases accelerate research while raising questions about ownership, consent, and equitable access.', 'checks' => ['How does a nucleosome package DNA?', 'How do plasmids differ from chromosomes?', 'Why does organization affect expression?'], 'misconception' => 'Most DNA is not continuously translated into protein.', 'videos' => ['Unit-3/Chapter-6/DNA Organization in Eukaryotes and Prokaryotes..mp4', 'Unit-3/Chapter-7/Genomes and Gene Organization.mp4']],
                ['id' => 'u3_replication', 'title' => '3.3 DNA Replication, Repair, and Aging', 'expectations' => ['D3.1'], 'vocabulary' => 'semiconservative, helicase, primase, DNA polymerase, ligase, leading strand, lagging strand, telomere, repair', 'explanation' => 'Replication is semiconservative and proceeds through coordinated enzyme action. Antiparallel strands require continuous leading-strand synthesis and discontinuous lagging-strand synthesis. Proofreading and repair reduce errors; telomere dynamics and accumulated damage connect genome maintenance with aging.', 'example' => 'Label a replication fork and justify the direction of each new strand from polymerase constraints.', 'stse' => 'Cancer therapies may target replication or repair, creating benefits and risks for rapidly dividing healthy tissue.', 'checks' => ['Why are Okazaki fragments required?', 'How do proofreading and repair differ?', 'What problem do telomeres address?'], 'misconception' => 'DNA polymerase cannot begin a strand without a primer or synthesize in both directions.', 'videos' => ['Unit-3/Chapter-6/DNA Replication and Repair.mp4', 'Unit-3/Chapter-6/DNA Replication and Aging.mp4']],
                ['id' => 'u3_transcription', 'title' => '3.4 Transcription and RNA Processing', 'expectations' => ['D2.1', 'D3.2', 'D3.3'], 'vocabulary' => 'template strand, RNA polymerase, promoter, mRNA, intron, exon, splicing, 5-prime cap, poly-A tail', 'explanation' => 'RNA polymerase builds complementary RNA from a DNA template. Eukaryotic transcripts are processed before export; capping, polyadenylation, and splicing influence stability and translation. Alternative splicing allows one gene to contribute to multiple products.', 'example' => 'Transcribe a short DNA template, identify RNA direction, and predict the effect of removing an exon.', 'stse' => 'RNA-based diagnostics and therapies depend on sequence, processing, delivery, and off-target risk.', 'checks' => ['Which DNA strand is read?', 'Why is RNA processed?', 'How can alternative splicing expand protein diversity?'], 'misconception' => 'Transcription copies a selected gene region, not an entire chromosome.', 'videos' => ['Unit-3/Chapter-7/Transcription-DNA-Directed RNA Synthesis.mp4']],
                ['id' => 'u3_translation', 'title' => '3.5 Translation and the Genetic Code', 'expectations' => ['D2.2', 'D2.4', 'D3.2', 'D3.3'], 'vocabulary' => 'codon, anticodon, tRNA, rRNA, ribosome, start codon, stop codon, polypeptide', 'explanation' => 'Ribosomes read mRNA codons and coordinate charged tRNAs to build a polypeptide. The genetic code is redundant but not ambiguous. Initiation establishes the reading frame; elongation forms peptide bonds; termination releases the chain for folding and modification.', 'example' => 'Translate an mRNA sequence, then analyse how an insertion changes every downstream codon.', 'stse' => 'Sequence interpretation supports pathogen surveillance and diagnosis but depends on sampling and model assumptions.', 'checks' => ['What establishes the reading frame?', 'Why is the code redundant?', 'How do tRNA and rRNA contribute?'], 'misconception' => 'A gene does not directly become a protein; information passes through regulated RNA and translation steps.', 'videos' => ['Unit-3/Chapter-7/Translation-Nucleic Acid to Polypeptide.mp4', 'Unit-3/Chapter-7/From Gene to Protein.mp4']],
                ['id' => 'u3_regulation', 'title' => '3.6 Regulation of Gene Expression', 'expectations' => ['D3.3'], 'vocabulary' => 'operon, repressor, activator, transcription factor, enhancer, epigenetic modification, differentiation', 'explanation' => 'Cells regulate expression at chromatin, transcriptional, RNA-processing, translational, and protein levels. Prokaryotic operons coordinate related genes; eukaryotic regulation integrates many signals. Differential expression allows cells with the same genome to specialize.', 'example' => 'Predict transcription when an inducible operon has or lacks its substrate and explain the role of the repressor.', 'stse' => 'Epigenetic research links environment and expression but does not justify deterministic claims about complex traits.', 'checks' => ['How does an operon coordinate genes?', 'Why do cell types differ?', 'At what stages can expression be controlled?'], 'misconception' => 'Turning a gene “off” does not remove it from the genome.', 'videos' => ['Unit-3/Chapter-7/Controlling Gene Expression.mp4']],
                ['id' => 'u3_mutations', 'title' => '3.7 Mutations, Viruses, and Genetic Change', 'expectations' => ['D3.4'], 'vocabulary' => 'substitution, insertion, deletion, frameshift, mutagen, somatic, germline, virus, reverse transcriptase', 'explanation' => 'Mutations change nucleotide sequence; effects depend on location, type, reading frame, and cellular context. Repair prevents many changes, while unrepaired mutations can be neutral, harmful, or beneficial. Viruses use host systems and can introduce or rearrange genetic material.', 'example' => 'Compare silent, missense, nonsense, and frameshift outcomes from changes to the same coding sequence.', 'stse' => 'Radiation and chemical exposure policies balance evidence about dose, benefit, and mutagenic risk.', 'checks' => ['Why can the same mutation type have different effects?', 'Which mutations are heritable?', 'How do viruses depend on host cells?'], 'misconception' => 'Mutation is not automatically harmful and does not occur because an organism “needs” a trait.', 'videos' => ['Unit-3/Chapter-7/Genetic Mutations.mp4', 'Unit-3/Chapter-7/Viruses-A Special Case.mp4']],
                ['id' => 'u3_tools', 'title' => '3.8 Manipulating and Cloning DNA', 'expectations' => ['D2.3', 'D3.5', 'D3.6'], 'vocabulary' => 'restriction enzyme, ligase, vector, plasmid, recombinant DNA, transformation, PCR, gel electrophoresis', 'explanation' => 'Biotechnology isolates, amplifies, separates, and recombines DNA. Restriction enzymes and ligase build recombinant molecules; vectors carry DNA; PCR amplifies defined regions; gel electrophoresis separates fragments by size. Controls are required to interpret results.', 'example' => 'Design a restriction-digest and gel plan that distinguishes recombinant from non-recombinant plasmids.', 'stse' => 'Genetic modification can improve production but requires ecological, health, ownership, and access analysis.', 'checks' => ['What does each PCR step accomplish?', 'How does a gel separate fragments?', 'Why are plasmids useful vectors?'], 'misconception' => 'A visible gel band represents many molecules of similar size, not one DNA molecule.', 'videos' => ['Unit-3/Chapter-8/Lesson 8.1 Manipulating and Cloning DNA.mp4', 'Unit-3/Chapter-8/07a_biotechnological_tools_&_techniques.mp4']],
                ['id' => 'u3_sequencing', 'title' => '3.9 DNA Sequencing and Bioinformatics', 'expectations' => ['D2.2', 'D3.5'], 'vocabulary' => 'sequencing, read, reference genome, alignment, variant, coverage, bioinformatics', 'explanation' => 'Sequencing determines nucleotide order through many measured fragments that software assembles or aligns. Coverage, read quality, contamination, and reference choice affect confidence. A detected variant requires biological and clinical interpretation rather than automatic classification.', 'example' => 'Examine simplified sequence reads, identify a consistent variant, and separate measurement uncertainty from biological inference.', 'stse' => 'Genomic testing raises consent, privacy, incidental-finding, and discrimination questions.', 'checks' => ['Why is coverage important?', 'What is the role of a reference genome?', 'Why is a variant not automatically disease-causing?'], 'misconception' => 'Sequencing output is not a perfectly certain, self-interpreting genome.', 'videos' => ['Unit-3/Chapter-8/Lesson 8.2 DNA sequencing.mp4', 'Unit-3/Chapter-8/Lesson 8.2 DNAsequencing(2).mp4']],
                ['id' => 'u3_ethics', 'title' => '3.10 Biotechnology, Health, Law, and Ethics', 'expectations' => ['D1.1', 'D1.2'], 'vocabulary' => 'bioethics, patent, regulation, genetic privacy, cloning, transgenic, informed consent', 'explanation' => 'Biotechnology decisions combine scientific evidence with ethical principles, law, economics, and social impact. Canadian regulation can be compared with other jurisdictions by examining purpose, evidence thresholds, oversight, and affected communities.', 'example' => 'Evaluate a genetic-health technology using benefits, risks, consent, ownership, access, and regulatory evidence.', 'stse' => 'The strongest position acknowledges uncertainty and competing values while citing reliable evidence.', 'checks' => ['Who benefits and who bears risk?', 'What evidence should regulation require?', 'How should genetic information be protected?'], 'misconception' => 'A technology being scientifically possible does not settle whether or how it should be used.', 'videos' => ['Unit-3/Chapter-8/Biotechnology and Health.mp4']],
            ],
            'practice' => ['DNA Sequence and Protein Synthesis Analysis', 'Biotechnology Evidence and Ethics Brief'],
            'lab' => 'DNA extraction and virtual PCR/gel analysis with safe supplied data',
            'assignment' => 'Prepare an evidence-based Canadian biotechnology policy recommendation.',
        ],
        4 => [
            'section' => 5,
            'title' => 'Unit 4 - Homeostasis',
            'book' => 'Learning Material - Unit 4: Homeostasis',
            'overall' => ['E1', 'E2', 'E3'],
            'chapters' => [
                ['id' => 'u4_feedback', 'title' => '4.1 Internal Balance and Feedback Systems', 'expectations' => ['E2.1', 'E2.2', 'E2.3'], 'vocabulary' => 'homeostasis, stimulus, receptor, control centre, effector, set range, negative feedback, positive feedback', 'explanation' => 'Homeostasis maintains variables within functional ranges through sensors, integrating centres, and effectors. Negative feedback reverses deviation; positive feedback amplifies a process until an external endpoint. Models must identify variable, signal, response, and feedback direction.', 'example' => 'Construct and annotate a feedback loop for body temperature, including disturbances and limits.', 'stse' => 'Monitoring technologies provide data but do not replace physiological interpretation or clinical judgment.', 'checks' => ['What distinguishes negative from positive feedback?', 'Why are set points often ranges?', 'How can a feedback loop fail?'], 'misconception' => 'Homeostasis is dynamic regulation, not an unchanging internal state.', 'videos' => ['Unit-4/Chapter-9/Ch-9 L-9.1 Maintaining an internal balance.mp4', 'Unit-4/Chapter-9/U-4 Ch-9 L-9.2Homeostasis and Feedback Mechanisms..mp4']],
                ['id' => 'u4_temperature_water', 'title' => '4.2 Thermoregulation and Water Balance', 'expectations' => ['E3.3'], 'vocabulary' => 'thermoregulation, vasodilation, vasoconstriction, osmoregulation, ADH, aldosterone, osmolarity', 'explanation' => 'Temperature regulation coordinates circulation, sweating, shivering, and metabolism. Water and ion balance depends on intake, loss, kidney function, and hormones. Feedback responses trade short-term correction against energy and resource costs.', 'example' => 'Predict changes in ADH, urine volume, and urine concentration after dehydration.', 'stse' => 'Heat exposure and water access are public-health issues shaped by climate, work, housing, and medical risk.', 'checks' => ['How does vasodilation affect heat loss?', 'What triggers ADH release?', 'Why are water and ion balance linked?'], 'misconception' => 'Drinking excessive water is not always harmless; severe imbalance can disrupt cell function.', 'videos' => ['Unit-4/Chapter-9/U-4-Ch-9 L-9.3 Thermoregulation.mp4', 'Unit-4/Chapter-9/U-4- Ch-9 -L- 9.4 Water Balance.mp4']],
                ['id' => 'u4_excretory', 'title' => '4.3 Excretory System and the Nephron', 'expectations' => ['E3.1', 'E3.3'], 'vocabulary' => 'kidney, nephron, filtration, reabsorption, secretion, loop of Henle, dialysis, acid-base balance', 'explanation' => 'Nephrons filter plasma, selectively reabsorb useful substances, secrete additional wastes, and establish gradients that concentrate urine. Kidneys regulate water, ions, pH, and waste removal while interacting with endocrine and circulatory systems.', 'example' => 'Trace water, glucose, sodium, and urea through nephron regions and predict consequences of impaired reabsorption.', 'stse' => 'Dialysis replaces selected kidney functions but differs in timing, selectivity, and regulation.', 'checks' => ['How do filtration and reabsorption differ?', 'Why is the medullary gradient important?', 'How do kidneys support pH balance?'], 'misconception' => 'Urine is not simply “filtered blood”; extensive selective processing follows filtration.', 'videos' => ['Unit-4/Chapter-9/9.5 The Excretory System.mp4']],
                ['id' => 'u4_endocrine', 'title' => '4.4 Endocrine Glands and Hormonal Signalling', 'expectations' => ['E2.1', 'E3.1'], 'vocabulary' => 'hormone, target cell, receptor, pituitary, thyroid, adrenal, pancreas, hypothalamus', 'explanation' => 'Endocrine glands release hormones into circulation. Only cells with appropriate receptors respond, and response depends on concentration, receptor signalling, and feedback. The hypothalamus and pituitary coordinate many axes linking nervous and endocrine control.', 'example' => 'Map a hypothalamic-pituitary-target gland axis and predict the effect of excessive target hormone.', 'stse' => 'Hormone measurements must be interpreted with timing, feedback, medications, and biological variation.', 'checks' => ['What makes a cell a target?', 'How does feedback regulate an endocrine axis?', 'How do nervous and endocrine signalling differ?'], 'misconception' => 'Hormones do not affect every cell equally just because they circulate in blood.', 'videos' => ['Unit-4/Chapter-10/CH-10 The Endocrine System.mp4', 'Unit-4/Chapter-10/10.2 the endocrine glands.mp4']],
                ['id' => 'u4_glucose', 'title' => '4.5 Blood Glucose Regulation', 'expectations' => ['E2.2', 'E3.1'], 'vocabulary' => 'insulin, glucagon, glycogenesis, glycogenolysis, pancreas, receptor, diabetes', 'explanation' => 'Rising blood glucose promotes insulin-mediated uptake and storage; falling glucose promotes glucagon-mediated release. The opposing pathways form negative feedback. Type 1 and type 2 diabetes disrupt different parts of this regulatory system.', 'example' => 'Interpret glucose and insulin curves after a meal and identify evidence of altered sensitivity.', 'stse' => 'Treatment access, monitoring technology, nutrition, and social determinants influence diabetes outcomes.', 'checks' => ['How do insulin and glucagon oppose each other?', 'What tissues store glucose?', 'How do diabetes types differ mechanistically?'], 'misconception' => 'Insulin does not directly “destroy sugar”; it changes transport and metabolism.', 'videos' => ['Unit-4/Chapter-10/10.3-Regulating Blood Sugar.mp4']],
                ['id' => 'u4_steroids_repro', 'title' => '4.6 Steroids and Reproductive Hormone Feedback', 'expectations' => ['E1.1', 'E3.2'], 'vocabulary' => 'steroid hormone, testosterone, estrogen, progesterone, FSH, LH, receptor, performance enhancement', 'explanation' => 'Steroid hormones cross membranes and alter gene expression through intracellular receptors. Reproductive axes use feedback among hypothalamus, pituitary, and gonads. External hormone use can disrupt feedback, affecting multiple body systems.', 'example' => 'Predict hormone changes when an external androgen suppresses hypothalamic and pituitary signalling.', 'stse' => 'Performance-enhancing substances require analysis of intended benefit, dose, evidence, fairness, and short- and long-term risk.', 'checks' => ['How do steroid hormones signal?', 'Where does feedback occur?', 'Why can external hormones reduce natural production?'], 'misconception' => '“Natural” and “synthetic” do not by themselves determine safety; dose and biological action matter.', 'videos' => ['Unit-4/Chapter-10/10.5 Steroids.mp4', 'Unit-4/Chapter-10/10.7 Reproductive system.mp4']],
                ['id' => 'u4_nervous', 'title' => '4.7 Nervous System and Nerve Signals', 'expectations' => ['E2.1', 'E3.1'], 'vocabulary' => 'neuron, membrane potential, action potential, depolarization, repolarization, synapse, neurotransmitter, acetylcholine', 'explanation' => 'Neurons maintain ion gradients and generate all-or-none action potentials when threshold is reached. Signals propagate along axons and cross chemical synapses through neurotransmitter release, receptor binding, and signal termination.', 'example' => 'Use an action-potential graph to locate channel events, refractory period, and directionality.', 'stse' => 'Drugs that alter neurotransmission may provide therapeutic benefit while producing side effects and dependence risks.', 'checks' => ['What establishes resting potential?', 'Why are action potentials one-directional?', 'How is a synaptic signal ended?'], 'misconception' => 'A stronger stimulus does not make each action potential larger; it can change firing frequency.', 'videos' => ['Unit-4/Chapter-11/CH-11 The Nervous System.mp4', 'Unit-4/Chapter-11/11.2-Nerve Signals.mp4']],
                ['id' => 'u4_cns_pns', 'title' => '4.8 Central and Peripheral Nervous Systems', 'expectations' => ['E3.1'], 'vocabulary' => 'central nervous system, peripheral nervous system, somatic, autonomic, sympathetic, parasympathetic, reflex arc', 'explanation' => 'The central nervous system integrates information; peripheral pathways carry sensory input and motor output. Somatic and autonomic divisions control different effectors, while sympathetic and parasympathetic activity balance readiness and recovery.', 'example' => 'Trace a reflex arc and explain why the spinal response can occur before conscious perception.', 'stse' => 'Neurological injury assessment links observed function to pathway location while recognizing limits of simple localization.', 'checks' => ['How do CNS and PNS roles differ?', 'What is a reflex arc?', 'How do autonomic divisions interact?'], 'misconception' => 'Parasympathetic and sympathetic systems are not simply “on” and “off”; their effects vary by organ.', 'videos' => ['Unit-4/Chapter-11/11.3-The central Nervous System.mp4', 'Unit-4/Chapter-11/11.4-The Peripheral Nervous System.mp4']],
                ['id' => 'u4_senses_environment', 'title' => '4.9 Sensory Systems and Environmental Health', 'expectations' => ['E1.2', 'E2.4', 'E3.1'], 'vocabulary' => 'sensory receptor, transduction, adaptation, stimulus, threshold, endocrine disruptor, environmental exposure', 'explanation' => 'Sensory receptors transduce environmental energy into neural signals. Adaptation and thresholds shape perception. Environmental chemicals and conditions can affect nervous, endocrine, respiratory, and other systems; causal claims require exposure and population evidence.', 'example' => 'Design a safe stimulus-response investigation using an invertebrate simulation or supplied observation data.', 'stse' => 'Evaluate environmental-health evidence by separating hazard from exposure and considering vulnerable populations.', 'checks' => ['What is transduction?', 'Why can perception change during constant stimulation?', 'How should environmental-health claims be evaluated?'], 'misconception' => 'Failure to perceive a stimulus does not prove that no biological exposure or effect exists.', 'videos' => ['Unit-4/Chapter-11/11.5-The Senses.mp4']],
            ],
            'practice' => ['Homeostatic Feedback Model and Data Analysis', 'Neural-Endocrine Case Study'],
            'lab' => 'Safe feedback-system investigation using simulation and supplied physiological data',
            'assignment' => 'Analyse a homeostatic disorder or environmental-health issue across interacting systems.',
        ],
        5 => [
            'section' => 6,
            'title' => 'Unit 5 - Population Dynamics',
            'book' => 'Learning Material - Unit 5: Population Dynamics',
            'overall' => ['F1', 'F2', 'F3'],
            'chapters' => [
                ['id' => 'u5_characteristics', 'title' => '5.1 Population Characteristics and Sampling', 'expectations' => ['F2.1', 'F3.2'], 'vocabulary' => 'population, density, distribution, fecundity, mortality, minimum viable population, quadrat, mark-recapture', 'explanation' => 'Populations are described by size, density, spatial distribution, age structure, birth and death rates, and viability. Sampling estimates these properties when a census is impractical. Method assumptions and sampling design determine reliability.', 'example' => 'Calculate a mark-recapture estimate, then explain how migration or unequal capture probability could bias it.', 'stse' => 'Wildlife management decisions depend on transparent uncertainty, repeated sampling, and ecological context.', 'checks' => ['Which characteristics describe a population?', 'When is a quadrat suitable?', 'What assumptions support mark-recapture?'], 'misconception' => 'A precise numerical estimate is not necessarily accurate if sampling assumptions fail.', 'videos' => ['Unit-5/Chapter-12/U-5 L-12.1 Population Characteristics.mp4']],
                ['id' => 'u5_demography', 'title' => '5.2 Demography and Population Change', 'expectations' => ['F3.2'], 'vocabulary' => 'demography, age structure, survivorship, natality, mortality, immigration, emigration', 'explanation' => 'Population change reflects births, deaths, immigration, and emigration. Age structure and survivorship patterns help predict future change, but projections depend on assumptions about rates and social or environmental conditions.', 'example' => 'Interpret contrasting age-structure diagrams and justify which population is likely to grow, stabilize, or decline.', 'stse' => 'Demographic planning connects population evidence with housing, health, education, and resource decisions.', 'checks' => ['What terms change population size?', 'How does age structure influence projection?', 'Why can rates change over time?'], 'misconception' => 'A large population is not necessarily growing rapidly; growth depends on rates and structure.', 'videos' => ['Unit-5/Chapter-12/U-5 L-12.2 Demography.mp4']],
                ['id' => 'u5_growth_models', 'title' => '5.3 Population Growth Models', 'expectations' => ['F2.2', 'F2.3', 'F3.3'], 'vocabulary' => 'exponential growth, logistic growth, intrinsic rate, carrying capacity, sigmoid, population cycle', 'explanation' => 'Exponential models assume a constant per-capita rate and unlimited resources. Logistic models slow as population approaches carrying capacity. Models simplify reality; comparison with data reveals where density dependence, time lags, disturbance, or migration matter.', 'example' => 'Calculate successive population sizes with an exponential model and compare them with a logistic curve and observed data.', 'stse' => 'Model projections support conservation and public planning but should include uncertainty and scenario assumptions.', 'checks' => ['When is exponential growth plausible?', 'What does carrying capacity represent?', 'Why might a population overshoot?'], 'misconception' => 'Carrying capacity is not a fixed universal number; it changes with environment and resource use.', 'videos' => ['Unit-5/Chapter-12/02_population_growth.mp4', 'Unit-5/Chapter-12/U-5 L-12.4 Factors that affect the population growth.mp4']],
                ['id' => 'u5_interactions', 'title' => '5.4 Species Interactions and Population Cycles', 'expectations' => ['F2.3', 'F3.1', 'F3.3', 'F3.5'], 'vocabulary' => 'competition, predation, mutualism, commensalism, parasitism, density-dependent, density-independent', 'explanation' => 'Interactions alter survival and reproduction. Predator-prey and competition dynamics can create cycles or shifts across food webs. Density-dependent effects strengthen with crowding, while many disturbances act independently of density.', 'example' => 'Analyse time-series data to test whether predator change follows prey change and consider alternative explanations.', 'stse' => 'Species management can create indirect effects across an ecosystem, so interventions require system-level evidence.', 'checks' => ['How do interaction types affect partners?', 'What distinguishes density dependence?', 'Why can one population affect many others?'], 'misconception' => 'Correlation between predator and prey cycles does not by itself prove a single causal pathway.', 'videos' => ['Unit-5/Chapter-12/U-5 Lesson-12.5 Interaction between individuals.mp4']],
                ['id' => 'u5_human_pop', 'title' => '5.5 Human Population Patterns and Geography', 'expectations' => ['F1.1', 'F3.2', 'F3.4'], 'vocabulary' => 'human demography, demographic transition, urbanization, migration, food energy, distribution', 'explanation' => 'Human populations vary in age structure, fertility, mortality, migration, and spatial distribution. Food systems transfer energy through production, distribution, and consumption, with losses at each stage. Geography and social conditions shape demographic patterns.', 'example' => 'Compare demographic indicators for two hypothetical regions without treating development as a single linear outcome.', 'stse' => 'Population analysis must avoid blaming groups and instead examine consumption, technology, policy, and unequal resource access.', 'checks' => ['Which factors shape human distribution?', 'How does food energy flow through systems?', 'Why do projections differ?'], 'misconception' => 'Environmental impact cannot be inferred from population size alone; per-capita consumption and technology matter.', 'videos' => ['Unit-5/Chapter-13/U-5 L-13.1Human population past and present.pptx.mp4', 'Unit-5/Chapter-13/U-5 L-13.1 (2)  Human Demographics.pptx.mp4', 'Unit-5/Chapter-13/11 Population geog.mp4']],
                ['id' => 'u5_footprint', 'title' => '5.6 Growth, Consumption, and Ecological Footprints', 'expectations' => ['F1.1', 'F3.4'], 'vocabulary' => 'ecological footprint, biocapacity, consumption, waste, sustainability, life-cycle analysis', 'explanation' => 'Ecological footprint analysis estimates biologically productive area needed to support consumption and absorb wastes. Population, consumption patterns, production technology, and distribution all contribute. Indicators are useful but depend on boundaries and assumptions.', 'example' => 'Compare two scenarios that hold population constant but change diet, transport, energy source, and waste.', 'stse' => 'Sustainability arguments should distinguish individual choices from infrastructure and policy constraints.', 'checks' => ['What factors shape a footprint?', 'What does biocapacity measure?', 'Which assumptions limit comparisons?'], 'misconception' => 'A footprint is a modelled indicator, not a direct complete measure of every environmental effect.', 'videos' => ['Unit-5/Chapter-13/L-13.2 Implications of Human population Growth.mp4', 'Unit-5/Chapter-13/U-5 L-13.2.pptx.mp4', 'Unit-5/Chapter-13/Presentation Important terms.mp4']],
                ['id' => 'u5_solutions', 'title' => '5.7 Population Sustainability and Canadian Initiatives', 'expectations' => ['F1.2'], 'vocabulary' => 'sustainable development, food security, conservation, biotechnology, initiative, effectiveness, equity', 'explanation' => 'Initiatives intended to support expanding populations can be assessed by goals, mechanisms, evidence of outcomes, unintended effects, cost, equity, and durability. Canadian technologies and programs should be evaluated with current evidence and affected-community perspectives.', 'example' => 'Develop criteria and evaluate a hypothetical food-fortification, crop, or habitat-restoration initiative.', 'stse' => 'A strong evaluation weighs benefits and risks rather than labelling a technology universally good or bad.', 'checks' => ['What counts as effectiveness?', 'How should equity be assessed?', 'What evidence reveals unintended effects?'], 'misconception' => 'Technological improvement alone cannot resolve sustainability without considering distribution and consumption.', 'videos' => ['Unit-5/Chapter-13/U_5 L-13.4.pptx.mp4']],
            ],
            'practice' => ['Population Sampling and Growth Model Analysis', 'Ecological Footprint Evidence Brief'],
            'lab' => 'Population simulation investigation with model comparison and error analysis',
            'assignment' => 'Evaluate a Canadian population-sustainability initiative using ecological and social evidence.',
        ],
    ],
];
