<?php
declare(strict_types=1);

/* Nexus-authored course blueprint.  Attached videos/decks are source material supplied by the teacher. */
$tdj = static function(string $id, string $title, array $expectations, string $vocab, string $explanation, array $videos = [], array $decks = []): array {
    return [
        'id'=>$id, 'title'=>$title, 'expectations'=>$expectations, 'vocabulary'=>$vocab,
        'explanation'=>$explanation, 'videos'=>$videos, 'decks'=>$decks,
        'checks'=>['What design decision is being justified?','Which evidence or constraint matters most?','What would you test or revise next?'],
        'task'=>'Create a labelled artefact, sketch, analysis, or reflection that makes your design reasoning visible.',
    ];
};
$avi = static function(string $id, string $title, array $expectations, string $vocab, string $explanation): array {
    return ['id'=>$id,'title'=>$title,'expectations'=>$expectations,'vocabulary'=>$vocab,'explanation'=>$explanation,
        'checks'=>['What visual choice communicates your intention?','What evidence from the artwork or process supports your interpretation?','What will you experiment with or revise next?'],
        'task'=>'Make a small study, document the process, and write a concise reflection using correct visual-arts terminology.'];
};
return [
 'tdj3m'=>[
  'courseid'=>170,'shortname'=>'TDJ3M','title'=>'Technological Design, Grade 11, University/College Preparation',
  'curriculum'=>'The Ontario Curriculum, Grades 11 and 12: Technological Education, 2009 (revised)',
  'units'=>[
   1=>['section'=>1,'title'=>'Unit 1 - Design Foundations','book'=>'Learning Material - Unit 1: Design Foundations','overall'=>['A1','A2','A5','B1','B2'], 'chapters'=>[
    $tdj('u1_theory','1.1 Design Theory and the Design Process',['A1.1','A1.2','A1.4','A5.4'],'need, problem, opportunity, function, form, ergonomics, innovation, sustainability, design process','Technological design responds to a human or environmental need through a repeatable process: define, research, generate, select, develop, model, test, improve, and communicate. A good brief separates the client need from a preferred solution and keeps criteria measurable.',['Unit 1/1-1-2_Design_Theory.mp4'],['Unit 1/1-1-2-Design Theory.pptx']),
    $tdj('u1_thinking','1.2 Design Thinking, Needs, and Research',['A1.2','A1.5','A2.1','B1.1'],'client, stakeholder, empathy, interview, research question, criterion, constraint, context, source','Design thinking makes the user and context visible before solutions are selected. Gather primary and secondary evidence, identify criteria and constraints, and record source quality. A design brief should name the user, need, context, deliverables, budget, materials, timeline, and success measures.',['Unit 1/1-2-2_Design_Thinking.mp4'],['Unit 1/1-2-2-Design Thinking.pptx']),
    $tdj('u1_types','1.3 Types of Design and Concept Development',['A1.3','A1.4','B2.1','B2.3'],'architectural, industrial, mechanical, apparel, artistic, technical, concept, ideation, iteration','Products can be artistic, technical, architectural, mechanical, industrial, or hybrid. Brainstorm quantity first, then compare concepts against criteria, resources, safety, cultural context, and environmental impact. Iteration is evidence-led change, not decoration after the fact.',['Unit 1/1-3-2_Types_of_Design.mp4'],['Unit 1/1-3-2-Types of Designs.pptx']),
    $tdj('u1_elements','1.4 Elements of Design in the Built Environment',['A1.1','A1.6','A3.1','B2.5'],'line, shape, form, space, colour, texture, balance, emphasis, proportion, circulation, accessibility','Elements and principles organize visual communication and user experience. In building design, scale, proportion, circulation, light, colour, texture, and accessibility affect how a space is understood and used. Explain how a choice serves both appearance and function.',['Unit 1/1-4-2_Elements_of_Building_Design.mp4'],['Unit 1/1-4-2-Elements of Design.pptx']),
   ],'activities'=>['Design Process Exercise','Design Brief Challenge','Initial Design Project'],'major'=>'Unit 1 Initial Design Project: a researched design brief, three concepts, selection matrix, and refined concept presentation.'],
   2=>['section'=>2,'title'=>'Unit 2 - Technical Drawing and Visual Communication','book'=>'Learning Material - Unit 2: Technical Drawing and Visual Communication','overall'=>['A3','B2','B3'], 'chapters'=>[
    $tdj('u2_lettering','2.1 Engineering Lettering and Annotation',['A3.2','A5.1','B2.4'],'lettering, baseline, cap height, guide line, annotation, title block, legibility, standard','Technical lettering makes a drawing readable and reproducible. Use consistent height, spacing, line weight, labels, symbols, and title-block information. Annotation should identify what a viewer must know without crowding the drawing.',['Unit 2/2-1-2_Engineering_Lettering.mp4','Unit 2/Uploaded to LMS/2-1-2-Enginerring Lettering_LMS.mp4']),
    $tdj('u2_ortho','2.2 Orthographic Drawing',['A3.2','A3.3','B2.2','B2.4'],'orthographic, front view, top view, right-side view, hidden line, centre line, projection','Orthographic drawings communicate a three-dimensional object through coordinated two-dimensional views. Align views, use recognized line conventions, preserve scale, and include only dimensions that can be interpreted unambiguously.',['Unit 2/2-2-2_Orthographic_Drawing.mp4','Unit 2/Uploaded to LMS/2-2-2- Orthographic Drawing_LMS.mp4']),
    $tdj('u2_projection','2.3 Orthographic Projection and Working Drawings',['A3.2','A3.3','A5.4','B2.4','B3.2'],'projection, first-angle, third-angle, dimension, tolerance, scale, isometric, working drawing','Projection systems establish the relationship among views. Working drawings combine geometry, dimensions, tolerances, material notes, scale, and revision information so another person can make or assess the design.',['Unit 2/2-3-2_Orthographic_projection.mp4','Unit 2/Uploaded to LMS/2-3-2 Orthographic Projections_LMS.mp4']),
   ],'activities'=>['Lettering and Annotation Plate','Orthographic View Study','Working Drawing Package'],'major'=>'Unit 2 Technical Drawing Project: a complete, dimensioned, multi-view drawing package for a small designed object.'],
   3=>['section'=>3,'title'=>'Unit 3 - Design Development and Modelling','book'=>'Learning Material - Unit 3: Design Development and Modelling','overall'=>['A2','A4','B1','B3','B4'], 'chapters'=>[
    $tdj('u3_product','3.1 Product Design and Development',['A1.2','A2.2','B1.1','B3.1'],'product, development, user need, specification, feasibility, prototype, iteration','Product design turns research into a specification and then into increasingly resolved concepts. Development balances function, appearance, cost, materials, manufacturability, safety, and user feedback.',['Unit 3/3-1-2-Product Design and Development.mp4','Unit 3/3-1-2_Product_Design_vs development.mp4','Unit 3/Uploaded to LMS/3-1-2 Product Design and development_LMS.mp4']),
    $tdj('u3_principles','3.2 Principles of Design in Technical Solutions',['A1.3','A3.1','B2.5','B3.3'],'balance, emphasis, rhythm, unity, proportion, contrast, hierarchy, affordance','Design principles guide how parts relate and how users read a solution. Apply balance, emphasis, rhythm, contrast, proportion, and unity to a technical concept, then test whether the visual system improves comprehension and use.',['Unit 3/3-1-3 Principles of Design .mp4','Unit 3/3-1-3_Principles_of_design.mp4','Unit 3/Uploaded to LMS/3-1-3 Principles of design_LMS.mp4']),
    $tdj('u3_environment','3.3 Technology and the Environment',['C1.1','C1.2','C1.3','B3.3'],'life-cycle, embodied energy, renewable, recyclable, waste, stewardship, circular design','Environmental responsibility is considered across sourcing, manufacture, use, maintenance, and end-of-life. Compare material choices and processes, reduce waste, and document trade-offs rather than claiming that a single material is automatically sustainable.',['Unit 3/3-1-4 Technology and Environment.mp4','Unit 3/3-1-4_Technology_and_Environment.mp4','Unit 3/Uploaded to LMS/3-1-4 Technology and environment_LMS.mp4']),
    $tdj('u3_society','3.4 Technology and Society',['C2.1','C2.2','C2.3','A1.1','B4.2'],'culture, context, accessibility, ethics, equity, infrastructure, unintended consequence','Technological choices affect people differently. Investigate historical context, cultural meanings, accessibility, equity, and unintended consequences, then communicate whose needs are served and what evidence supports the decision.',['Unit 3/3-1-5 Technology and Society.mp4','Unit 3/3-1-5_Technology_and_Society.mp4','Unit 3/Uploaded to LMS/3-1-5 Technology and society_LMS.mp4']),
   ],'activities'=>['Product Research and Specification','Principles Applied Concept Sheet','Sustainable Materials Comparison','Technology-and-Society Case Brief'],'major'=>'Unit 3 Development Project: develop a concept from research through CAD or physical model, with a documented materials and STSE decision log.'],
   4=>['section'=>4,'title'=>'Unit 4 - Prototyping, Testing, and Improvement','book'=>'Learning Material - Unit 4: Prototyping, Testing, and Improvement','overall'=>['A4','B3','B4','C1','D1'], 'chapters'=>[
    $tdj('u4_environment_safety','4.1 Environment, Health, and Safety in Design',['C1.1','C1.2','C1.3','D1.1','D1.2'],'hazard, risk, PPE, ventilation, WHMIS, waste stream, ergonomics, hierarchy of controls','Safe design considers people, environment, tools, materials, and disposal. Identify hazards, assess risk, select controls and PPE, and document a safe operating procedure before building or testing.',['Unit 4/4-1-2_Environment_,_health_and_safety.mp4','Unit 4/Uploaded to LMS/4-1-2-Environment, health and Safety_LMS.mp4']),
    $tdj('u4_health_safety','4.2 Safe Processes and Responsible Workshop Practice',['D1.1','D1.2','D1.3','B3.1'],'safe operating procedure, guard, protective clothing, housekeeping, incident, emergency, inspection','Health and safety is an ongoing practice: inspect the workspace, use guards and protective equipment, control dust/noise/chemicals, keep pathways clear, and report incidents. Apply the same discipline to home or digital prototyping.',['Unit 4/4-1-3_Health_and_safety.mp4','Unit 4/Uploaded to LMS/4-1-3 Health and safety_LMS.mp4']),
    $tdj('u4_career_skills','4.3 Design Career Skills and Professional Practice',['A5.1','A5.2','B4.1','D2.5','D2.6'],'technical communication, teamwork, reliability, initiative, portfolio, client service, project management','Professional practice combines technical skill with communication, teamwork, planning, reliability, customer service, and initiative. Keep an up-to-date portfolio with drawings, photographs, logs, feedback, and reflections that prove what you can do.',['Unit 4/4-1-4_design_career_skills (1).mp4','Unit 4/Uploaded to LMS/4-1-4 Design career skills_LMS.mp4']),
    $tdj('u4_pathways','4.4 Careers and Pathways',['D2.1','D2.2','D2.3','D2.4','D2.7'],'architect, technologist, draftsperson, industrial designer, OACETT, PEO, pathway, apprenticeship','Design careers include architecture, drafting, industrial design, interior design, engineering technology, digital fabrication, and more. Compare secondary, college, university, apprenticeship, association, and mentorship pathways using current official program information.',['Unit 4/4-1-5_Careers_and_pathways (1).mp4','Unit 4/Uploaded to LMS/4-1-5 Career and pathways_LMS.mp4']),
   ],'activities'=>['Prototype Safety Plan','Prototype Build and Test','Career Portfolio Evidence'],'major'=>'Unit 4 Prototype Challenge: build or simulate a functional prototype, test against criteria, analyse failure, and submit an iteration report.'],
   5=>['section'=>5,'title'=>'Unit 5 - Design, Society, and Professional Portfolio','book'=>'Learning Material - Unit 5: Design, Society, and Professional Portfolio','overall'=>['A1','A2','A5','B4','C1','C2','D2'], 'chapters'=>[
    $tdj('u5_sustainable','5.1 Sustainable Design and Life-Cycle Decisions',['C1.1','C1.2','C1.3','B3.3'],'life-cycle assessment, circularity, repair, reuse, embodied carbon, durability','Use a life-cycle lens to compare sourcing, making, using, repairing, and disposing. Sustainable design is a reasoned set of trade-offs supported by evidence, not a marketing label.'),
    $tdj('u5_ethics','5.2 Ethical, Cultural, and Accessible Design',['A1.1','A1.5','A1.6','C2.2','C2.3'],'ethics, consent, inclusion, universal design, cultural context, bias, accessibility','Ethical design listens to affected users, respects culture and intellectual property, anticipates bias, and removes barriers. Evaluate who benefits, who may be harmed, and how consultation changes the brief.'),
    $tdj('u5_management','5.3 Project Management and Technical Reporting',['A2.2','A5.1','A5.2','A5.3','A5.4','B1.2','B4.1'],'scope, milestone, critical path, budget, risk register, technical report, revision history','A professional project plan makes scope, people, materials, budget, risks, milestones, and decisions visible. A technical report uses precise terminology, drawings, evidence, evaluation, and a clear design summary.'),
    $tdj('u5_portfolio','5.4 Portfolio, Presentation, and Reflection',['A5.2','A5.3','B4.1','B4.2','D2.7'],'portfolio, curation, presentation, audience, reflection, evidence, iteration','Curate process evidence so a viewer can follow the problem, research, ideas, development, testing, revision, and outcome. Present decisions for a real audience and reflect on next skills to develop.'),
    $tdj('u5_culminating','5.5 Culminating Design Project Studio',['A1.1','A1.2','A1.5','A3.3','A4.3','A5.4','B2.4','B3.1','B3.3','B4.2','C1.2','C2.2','D2.7'],'design brief, criteria, constraints, concept, working drawing, prototype, test, evaluation, iteration, portfolio','The culminating project integrates the full design process. Define an authentic problem or opportunity, research and consult, set criteria and constraints, generate and select ideas, produce drawings and a model/prototype, test, improve, present, and reflect.'),
   ],'activities'=>['Sustainability Decision Matrix','Ethical Design Consultation','Project Management Pack','Portfolio Curation'],'major'=>'Culminating Design Project and Portfolio: complete the full design cycle and present a professional evidence portfolio.'],
  ],
 ],
 'avi2o'=>[
  'courseid'=>127,'shortname'=>'AVI2O','title'=>'Visual Arts, Grade 10, Open','curriculum'=>'The Ontario Curriculum, Grades 9 and 10: The Arts, 2010 (revised)','units'=>[
   1=>['section'=>1,'title'=>'Unit 1 - Elements and Principles of Art','book'=>'Learning Material - Unit 1: Elements and Principles of Art','overall'=>['A2','C1','C2'], 'chapters'=>[
    $avi('a1_elements','1.1 Elements: Line, Shape, Form, Space, and Texture',['A2.1','C1.1','C2.1'],'line, shape, form, space, texture, contour, positive space, negative space','Elements are the visual vocabulary of art. Line can describe contour and movement; shape organizes two-dimensional areas; form suggests or occupies volume; space creates depth; texture creates tactile or visual surface. Combine them intentionally to express an idea.',''),
    $avi('a1_colour_value','1.2 Colour and Value',['A2.1','A2.2','C1.1'],'hue, value, intensity, tint, shade, contrast, warm, cool, saturation','Colour relationships and value structure guide attention and mood. Build a value scale, test warm/cool and complementary relationships, and use contrast deliberately rather than adding colour without a compositional purpose.',''),
    $avi('a1_principles','1.3 Principles: Balance, Emphasis, Movement, Pattern, Rhythm, Unity, Variety',['A2.1','A2.2','C1.1'],'balance, emphasis, movement, pattern, rhythm, unity, variety, proportion','Principles describe relationships among elements. A focal point, repeated rhythm, balanced weight, and purposeful variety create visual hierarchy and unity. Analyse how a choice changes the viewer’s path through the work.',''),
    $avi('a1_composition','1.4 Composition Design Challenge',['A1.1','A1.2','A2.2','A3.1'],'thumbnail, composition, focal point, crop, iteration, mixed media','Use thumbnails to generate alternatives, select against a stated intention, experiment with media, and revise after feedback. Document the creative process in a sketchbook or digital portfolio.',''),
   ],'activities'=>['Elements Exploration','Composition Study','Design Challenge'],'major'=>'Unit 1 Composition Project: create an artwork that uses at least five elements and four principles, with process evidence and reflection.'],
   2=>['section'=>2,'title'=>'Unit 2 - Drawing and Observation','book'=>'Learning Material - Unit 2: Drawing and Observation','overall'=>['A1','A2','A3','C1','C2'], 'chapters'=>[
    $avi('a2_observation','2.1 Seeing and Recording Observation',['A1.1','A1.2','A2.1','C2.1'],'observation, contour, gesture, proportion, sighting, measuring, blind contour','Observation drawing trains attention to relationships rather than symbols. Use sighting, comparative measurement, contour, gesture, and blind-contour exercises to slow down looking and record evidence.',''),
    $avi('a2_space','2.2 Positive and Negative Space',['A2.1','A2.2','C1.1'],'positive space, negative space, overlap, scale, cropping, composition','Treat surrounding space as an active shape. Analyse overlap, scale, cropping, and intervals to create a convincing composition and to avoid drawing isolated objects without context.',''),
    $avi('a2_value','2.3 Value, Light, Shadow, Form, and Texture',['A2.1','A3.1','C2.1'],'value, highlight, halftone, core shadow, cast shadow, reflected light, texture','Value describes relative lightness and darkness. Build a light logic from a single source, distinguish form shadow from cast shadow, and imply texture through mark direction and edge control.',''),
    $avi('a2_major','2.4 Major Observation Drawing Project',['A1.2','A1.3','A2.1','A3.2','B1.4'],'study, revision, craftsmanship, presentation, artist statement','Plan a sustained drawing from observation, gather studies, revise from peer feedback, finish with careful presentation, and explain how choices communicate your intention.',''),
   ],'activities'=>['Observation Studies','Value/Form Study','Major Drawing Project'],'major'=>'Unit 2 Major Drawing: sustained observational artwork with studies, revisions, presentation, statement, and self-assessment.'],
   3=>['section'=>3,'title'=>'Unit 3 - Colour and Painting','book'=>'Learning Material - Unit 3: Colour and Painting','overall'=>['A1','A2','A3','C1','C2','C3'], 'chapters'=>[
    $avi('a3_theory','3.1 Colour Theory and the Colour Wheel',['A2.1','C1.1','C2.1'],'primary, secondary, tertiary, hue, value, intensity, complementary, analogous, triadic','A colour wheel helps predict relationships, but context changes perception. Mix clean secondaries and neutrals, compare analogous and complementary schemes, and connect palette to meaning or mood.',''),
    $avi('a3_mixing','3.2 Mixing, Warm/Cool, and Mood',['A1.2','A2.1','A2.2','C2.1'],'mixing, warm, cool, atmospheric, neutral, chroma, mood','Control value and intensity as carefully as hue. Warm/cool shifts can create spatial and emotional effects; a limited palette can create unity while a strategic accent creates emphasis.',''),
    $avi('a3_technique','3.3 Painting Techniques and Craftsmanship',['A3.1','C2.1','C3.2','C3.3'],'wash, glazing, dry brush, layering, opacity, edge, cleanup, recycled materials','Experiment with washes, layering, dry brush, opacity, and edges. Work safely, clean tools, manage water and waste, and choose materials with environmental responsibility.',''),
    $avi('a3_major','3.4 Major Painting Project',['A1.1','A1.2','A1.3','A2.2','A3.2','B1.4'],'concept, palette, underpainting, revision, presentation, statement','Develop a concept, test palette thumbnails, create a painting, seek feedback, revise, present, and write an artist statement that connects process, technique, and meaning.',''),
   ],'activities'=>['Colour Exploration','Painting Technique Study','Major Painting Project'],'major'=>'Unit 3 Major Painting: an original painting with colour plan, technique tests, process documentation, statement, and reflection.'],
   4=>['section'=>4,'title'=>'Unit 4 - Mixed Media, Design, and 3D','book'=>'Learning Material - Unit 4: Mixed Media, Design, and 3D','overall'=>['A1','A2','A3','C2','C3'], 'chapters'=>[
    $avi('a4_mixed','4.1 Mixed Media, Collage, and Texture',['A1.1','A1.2','A3.1','C2.1','C3.3'],'mixed media, collage, assemblage, layering, found object, texture, adhesion','Mixed media combines materials for conceptual and sensory effect. Test adhesion, layering, scale, and texture; record what changes when materials interact. Use found or recycled materials responsibly.',''),
    $avi('a4_design','4.2 Print and Graphic Design Experiments',['A2.2','A3.1','C1.2','C2.1'],'positive/negative, repeat, registration, typography, symbol, message','Design for an audience requires hierarchy, contrast, legibility, and reproducibility. Explore repeat, positive/negative shape, symbols, and type while keeping the message clear.',''),
    $avi('a4_3d','4.3 Sculpture, Form, and 3D Space',['A1.2','A2.1','A3.1','C2.1','C3.2'],'sculpture, additive, subtractive, armature, balance, scale, installation','Three-dimensional work occupies real space. Plan stability and armature, compare additive and subtractive processes, and consider how viewers move around or through the form.',''),
    $avi('a4_major','4.4 Mixed-Media or 3D Major Project',['A1.1','A1.3','A2.2','A3.2','B1.4','C3.3'],'prototype, material test, craftsmanship, installation, critique, statement','Sustain a mixed-media or three-dimensional project from proposal through experimentation, making, critique, presentation, and reflection.',''),
   ],'activities'=>['Material Experiment','Print/Design Study','3D Form Study','Major Mixed-Media or 3D Project'],'major'=>'Unit 4 Major Artwork: an original mixed-media, print/design, sculpture, or installation work with material tests and critique evidence.'],
   5=>['section'=>5,'title'=>'Unit 5 - Art, Culture, and Personal Expression','book'=>'Learning Material - Unit 5: Art, Culture, and Personal Expression','overall'=>['A1','A2','B1','B2','B3','C1','C3'], 'chapters'=>[
    $avi('a5_context','5.1 Art, Culture, and Context',['B1.3','B2.1','B2.2','C1.1'],'culture, context, function, audience, historical, contemporary, symbolism','Artworks reflect the materials, beliefs, technologies, events, and audiences of their contexts. Interpret without flattening cultural differences, and use specific visual evidence to support claims.',''),
    $avi('a5_analysis','5.2 Critical Analysis and Interpretation',['B1.1','B1.2','B1.3','B1.4'],'description, analysis, interpretation, evaluation, evidence, critique','The critical analysis process moves from initial reaction to description, analysis of elements and principles, interpretation of meaning, evaluation, and reflection. Constructive critique names strengths, questions, and actionable next steps.',''),
    $avi('a5_voice','5.3 Responsible Imagery and Personal Voice',['A2.2','B2.3','C3.1','C3.3'],'identity, voice, appropriation, plagiarism, copyright, consent, representation','Personal expression can address identity and issues while respecting consent, copyright, cultural ownership, and representation. Distinguish inspiration from copying and cite source imagery or ideas.',''),
    $avi('a5_pathways','5.4 Visual Arts Skills and Pathways',['B3.1','B3.2','B3.3','A3.3'],'visual literacy, creative problem solving, graphic design, animation, portfolio, exhibition','Visual arts builds visual literacy, spatial organization, communication, creative problem solving, and presentation. Research pathways and community opportunities, then identify evidence in your portfolio.',''),
   ],'activities'=>['Artwork Context Analysis','Peer Critique','Artist Statement and Voice Study','Pathways Research'],'major'=>'Unit 5 Personal Expression Project: create an artwork grounded in research and context, then present a critique-ready statement and reflection.'],
  ],
 ],
];
